### PR TITLE
Super roach skr13 addition

### PR DESCRIPTION
**Pull request by SuperRoach**
This is the SKR1.3 Addition

### CODE REVIEW

**Comment by FHeilmann** [comment]
Thanks for the PR. @jdlongenecker can you take a look and see if this is viable?

One thing I would like you to do is remove the youtube link to your channel from the readme. This is not the place to promote your youtube channel.

Bests,
-Florian

**Comment by SuperRoach** [comment]
I've removed the youtube commit (understand the need about promotion, although it'd non monetised and was an exclusive voron 1 building playlist) and added mention and link to the voron discord. By wanting me to delete my fork, do you want me to remove all changes submitted for this?

**Comment by FHeilmann** [comment]
The closing was in error, apologies! Thanks for removing the link

**Comment by FHeilmann** [comment]
@SuperRoach I'm ready to merge this, however there are a few fixes that were made to the SKR1.4 config as part of #41. Could you look those over and apply the same fixes to this config?

**Comment by SuperRoach** [comment]
Thanks! I've done that now after looking at the changes that had been done elsewhere. There are some quality of life things that might be useful to add into the skr1.4 config as well (like naming screws, labelling led pixels etc, indicated in changelog)

**Comment by FHeilmann** [comment]
I'm starting to wonder if it would make sense to make BOARD_PINS cfg files for the two boards and then use one combined configuration for both boards. What's your opinion on that? 

I had a quick glance and your changes and noticed that the top of the config still says "Voron2". Also some comments mention the wrong pins (such as for the probe). Please fix those inconsistencies as well!

**Comment by SuperRoach** [comment]
I've never done a board_pins config, but the method in how the wiring is done is slightly different with how the pins are allocated and people do it between the two boards (power differences in the probe and SSR connections) so I'm not sure.

Reading the original PDF become more of a source of a truth for me over the course of actually finding out what the pins were.

Updated the text and added some more text explanations about why the probe pinout is different.

Did you see the comment on your 1.4 merge? There are some comments about what leadscrew pitch to use in this one that could be useful over there, and too high homing speeds still in it as well.

**Comment by eddietheengineer** [comment]
@SuperRoach sorry for letting this flounder for such a long time. I think the last remaining thing would be a wiring diagram for the board--I can probably create that in a separate pull request. Let me look over it and then we'll get them merged in!

**Comment by SuperRoach** [comment]
There is a pdf of wiring diagram from eddie, it's In #voron_v1_questions, as a pinned post. Probably a good seperate pull request.

Fingers crossed it gets in lol. Thanks for getting back.

**Comment by eddietheengineer** [comment]
Ooh, thanks for the reminder! We can pull that in too. I've been comparing the new SKR 1.3 config you have vs the SKR 1.4 config that I made, and there's quite a few nice formatting tweaks you made to the SKR 1.3 version that would be great with the 1.4 version as well. Would you mind if we merged your pull request and then I aligned the formatting between the two with a follow up PR?

**Comment by SuperRoach** [comment]
Yeah sure okay.

**Pull request merged**
